title: Yash Vyas
logo: /assets/img/Photo-circle.png
description: PhD in Robotics (University of Padua) | EU Marie Skłodowska-Curie Scholar | ETH Zürich (RSL & ASL) | MSc Robotics, ETH Zürich
show_downloads: false
theme: jekyll-theme-minimal
